### ISSUE TITLE
Revive #welcome

### ISSUE THREAD

**Issue by showierdata9978** [4dMinerCommunity/4d-discord-bot#1]

**Comment by redjard** [comment]
please clarify.

You want a message of some sort in the #welcome channel for anyone that joins?
Should it ping the newcomers or just mention them by name?
I could even make a nice graphical embed for them, kinda like the poll thing.
What are the messages? A randomly selected one from a configurable list?
should it have a 2% chance to tell one they are the 1 millionth member and redirect them to a scam page to claim their free iPhone Galaxy 16 Pro Max?
